<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
        <UseWinUI>true</UseWinUI>
        <WinUISDKReferences>false</WinUISDKReferences>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>PowerPlan.Tray</RootNamespace>
        <Platforms>x86;x64;ARM64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PowerPlan.Core\PowerPlan.Core.csproj" />
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
    </ItemGroup>
</Project>
